package enums;

import interfaces.Token;

/**
 * All possible magic effects
 * @author MarcoForlini
 */
@SuppressWarnings ("javadoc")
public enum TokenSpell implements Token {
	
	DEFAULT ("", null),
	ABAT ("ABAT", "Absorb Attribute"),
	ABFA ("ABFA", "Absorb Fatigue"),
	ABHE ("ABHE", "Absorb Health"),
	ABSK ("ABSK", "Absorb Skill"),
	ABSP ("ABSP", "Absorb Magicka"),
	BA01 ("BA01", "Bound Armor Extra 01"),
	BA02 ("BA02", "Bound Armor Extra 02"),
	BA03 ("BA03", "Bound Armor Extra 03"),
	BA04 ("BA04", "Bound Armor Extra 04"),
	BA05 ("BA05", "Bound Armor Extra 05"),
	BA06 ("BA06", "Bound Armor Extra 06"),
	BA07 ("BA07", "Bound Armor Extra 07"),
	BA08 ("BA08", "Bound Armor Extra 08"),
	BA09 ("BA09", "Bound Armor Extra 09"),
	BA10 ("BA10", "Bound Armor Extra 10"),
	BABO ("BABO", "Bound Boots"),
	BACU ("BACU", "Bound Cuirass"),
	BAGA ("BAGA", "Bound Gauntlets"),
	BAGR ("BAGR", "Bound Greaves"),
	BAHE ("BAHE", "Bound Helmet"),
	BASH ("BASH", "Bound Shield"),
	BRDN ("BRDN", "Burden"),
	BW01 ("BW01", "Bound Order Weapon 1"),
	BW02 ("BW02", "Bound Order Weapon 2"),
	BW03 ("BW03", "Bound Order Weapon 3"),
	BW04 ("BW04", "Bound Order Weapon 4"),
	BW05 ("BW05", "Bound Order Weapon 5"),
	BW06 ("BW06", "Bound Order Weapon 6"),
	BW07 ("BW07", "Summon Staff of Sheogorath"),
	BW08 ("BW08", "Bound Priest Dagger"),
	BW09 ("BW09", "Bound Weapon Extra 09"),
	BW10 ("BW10", "Bound Weapon Extra 10"),
	BWAX ("BWAX", "Bound Axe"),
	BWBO ("BWBO", "Bound Bow"),
	BWDA ("BWDA", "Bound Dagger"),
	BWMA ("BWMA", "Bound Mace"),
	BWSW ("BWSW", "Bound Sword"),
	CALM ("CALM", "Calm"),
	CHML ("CHML", "Chameleon"),
	CHRM ("CHRM", "Charm"),
	COCR ("COCR", "Command Creature"),
	COHU ("COHU", "Command Humanoid"),
	CUDI ("CUDI", "Cure Disease"),
	CUPA ("CUPA", "Cure Paralysis"),
	CUPO ("CUPO", "Cure Poison"),
	DARK ("DARK", "DO NOT USE - Darkness"),
	DEMO ("DEMO", "Demoralize"),
	DGAT ("DGAT", "Damage Attribute"),
	DGFA ("DGFA", "Damage Fatigue"),
	DGHE ("DGHE", "Damage Health"),
	DGSP ("DGSP", "Damage Magicka"),
	DIAR ("DIAR", "Disintegrate Armor"),
	DISE ("DISE", "Disease Info"),
	DIWE ("DIWE", "Disintegrate Weapon"),
	DRAT ("DRAT", "Drain Attribute"),
	DRFA ("DRFA", "Drain Fatigue"),
	DRHE ("DRHE", "Drain Health"),
	DRSK ("DRSK", "Drain Skill"),
	DRSP ("DRSP", "Drain Magicka"),
	DSPL ("DSPL", "Dispel"),
	DTCT ("DTCT", "Detect Life"),
	DUMY ("DUMY", "Mehrunes Dagon Custom Effect"),
	FIDG ("FIDG", "Fire Damage"),
	FISH ("FISH", "Fire Shield"),
	FOAT ("FOAT", "Fortity Attribute"),
	FOFA ("FOFA", "Fortity Fatigue"),
	FOHE ("FOHE", "Fortity Health"),
	FOMM ("FOMM", "Fortity Magicka Multiplier"),
	FOSK ("FOSK", "Fortity Skill"),
	FOSP ("FOSP", "Fortity Magicka"),
	FRDG ("FRDG", "Frost Damage"),
	FRNZ ("FRNZ", "Frenzy"),
	FRSH ("FRSH", "Frost Shield"),
	FTHR ("FTHR", "Feather"),
	INVI ("INVI", "Invisibility"),
	JRSH ("JRSH", "The Constant Physicist"),
	LGHT ("LGHT", "Light"),
	LISH ("LISH", "Shock Shield"),
	LOCK ("LOCK", "DO NOT USE - Lock"),
	MYHL ("MYHL", "Summon Mythic Dawn Helm"),
	MYTH ("MYTH", "Summon Mythic Dawn Armor"),
	NEYE ("NEYE", "Night-Eye"),
	OPEN ("OPEN", "Open"),
	PARA ("PARA", "Paralyze"),
	POSN ("POSN", "Poison Info"),
	RALY ("RALY", "Rally"),
	REAN ("REAN", "Reanimate"),
	REAT ("REAT", "Restore Attribute"),
	REDG ("REDG", "Reflect Damage"),
	REFA ("REFA", "Restore Fatigue"),
	REHE ("REHE", "Restore Health"),
	RESP ("RESP", "Restore Magicka"),
	RFLC ("RFLC", "Reflect Spell"),
	RSDI ("RSDI", "Resist Disease"),
	RSFI ("RSFI", "Resist Fire"),
	RSFR ("RSFR", "Resist Frost"),
	RSMA ("RSMA", "Resist Magic"),
	RSNW ("RSNW", "Resist Normal Weapons"),
	RSPA ("RSPA", "Resist Paralysis"),
	RSPO ("RSPO", "Resist Poison"),
	RSSH ("RSSH", "Resist Shock"),
	RSWD ("RSWD", "Resist Water Damage"),
	SABS ("SABS", "Spell Absorption"),
	SEFF ("SEFF", "Script Effect"),
	SHDG ("SHDG", "Shock Damage"),
	SHLD ("SHLD", "Shield"),
	SLNC ("SLNC", "Silence"),
	STMA ("STMA", "Stunted Magicka"),
	STRP ("STRP", "Soul Trap"),
	SUDG ("SUDG", "Sun Damage"),
	TELE ("TELE", "Telekinesis"),
	TURN ("TURN", "Turn Undead"),
	VAMP ("VAMP", "Vampirism"),
	WABR ("WABR", "Water Breathing"),
	WAWA ("WAWA", "Water Walking"),
	WKDI ("WKDI", "Weakness to Disease"),
	WKFI ("WKFI", "Weakness to Fire"),
	WKFR ("WKFR", "Weakness to Frost"),
	WKMA ("WKMA", "Weakness to Magic"),
	WKNW ("WKNW", "Weakness to Normal Weapons"),
	WKPO ("WKPO", "Weakness to Poison"),
	WKSH ("WKSH", "Weakness to Shock"),
	Z001 ("Z001", "Summon Rufio's Ghost"),
	Z002 ("Z002", "Summon Ancestor Guardian"),
	Z003 ("Z003", "Summon Spiderling"),
	Z004 ("Z004", "Summon Flesh Atronach"),
	Z005 ("Z005", "Summon Bear"),
	Z006 ("Z006", "Summon Gluttonous Hunger"),
	Z007 ("Z007", "Summon Ravenous Hunger"),
	Z008 ("Z008", "Summon Voracious"),
	Z009 ("Z009", "Summon Dark Seducer"),
	Z010 ("Z010", "Summon Golder Saint"),
	Z011 ("Z011", "Wabba Summon"),
	Z012 ("Z012", "Summon Decrepit Shambles"),
	Z013 ("Z013", "Summon Shambles"),
	Z014 ("Z014", "Summon Replete Shambles"),
	Z015 ("Z015", "Summon Hunger"),
	Z016 ("Z016", "Summon Mangled Flesh Atronach"),
	Z017 ("Z017", "Summon Torn Flesh Atronach"),
	Z018 ("Z018", "Summon Stiched Flesh Atronach"),
	Z019 ("Z019", "Summon Sewn Flesh Atronach"),
	Z020 ("Z020", "Extra Summon 20"),
	ZCLA ("ZCLA", "Summon Clannfear"),
	ZDAE ("ZDAE", "Summon Daedroth"),
	ZDRE ("ZDRE", "Summon Dremora"),
	ZDRL ("ZDRL", "Summon Dremora Lord"),
	ZFIA ("ZFIA", "Summon Flame Atronach"),
	ZFRA ("ZFRA", "Summon Frost Atronach"),
	ZGHO ("ZGHO", "Summon Ghost"),
	ZHDZ ("ZHDZ", "Summon Headless Zombie"),
	ZLIC ("ZLIC", "Summon Lich"),
	ZSCA ("ZSCA", "Summon Scamp"),
	ZSKA ("ZSKA", "Summon Skeleton Guardian"),
	ZSKC ("ZSKC", "Summon Skeleton Champion"),
	ZSKE ("ZSKE", "Summon Skeleton"),
	ZSKH ("ZSKH", "Summon Skeleton Hero"),
	ZSPD ("ZSPD", "Summon Spider Daedra"),
	ZSTA ("ZSTA", "Summon Storm Atronach "),
	ZWEA ("ZWEA", "Summon Faded Wraith"),
	ZWRL ("ZWRL", "Summon Gloom Wraith"),
	ZXIV ("ZXIV", "Summon Xivilai"),
	ZZOM ("ZZOM", "Summon Zombie"),
	;
	
	public final String code;
	public final String name;
	
	TokenSpell (String code, String name){
		this.code = code;
		this.name = name;
	}
	
	@Override
	public String toCode(){
		return code;
	}

	@Override
	public String toString(){
		if (name != null) {
			return '(' + code + ")   " + name;
		}
		return "";
	}
	
}
